#!/usr/bin/env python3
"""M0 spec audit: how far can each RE ``uber.hlsl`` be trusted as a specification?

Every retail key is rebuilt from its subfamily's ``uber.hlsl`` with the key's
local defines (SDK fxc, the same d3dcompiler family slangc drives) and judged
against the retail program exactly like a slang candidate: D2 declaration
surface, then the D4 differential with its full schedule and wide-mode
classification. The RE harness validated these ubers with register-aligned
outputs and no signature check; this is the audit with both.

The result is ``d3_perms/_spec_notes.md`` (one row per subfamily) and
``d3_perms/_spec_audit.json`` (one row per key). A slang author reads a
subfamily's row before trusting its uber.

    python tools/d3_spec_audit.py [--jobs 20] [--subfamily Prop.fx__ps_prop]
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import tempfile
import traceback
from collections import Counter, defaultdict
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import d3_decl_surface as D2              # noqa: E402
import d3_diff as DF                      # noqa: E402
import d3_drivers as DR                   # noqa: E402
import d3_dxbc as DX                      # noqa: E402
import d3_perm_manifest as M              # noqa: E402
import d3_retail as R                     # noqa: E402


def find_fxc() -> str:
    for root in (Path(r'C:\Program Files (x86)\Windows Kits\10\bin'),
                 Path(r'C:\Program Files\Windows Kits\10\bin')):
        found = sorted(root.glob('*/x64/fxc.exe'))
        if found:
            return str(found[-1])
    raise FileNotFoundError('fxc.exe not found in the Windows SDK')


def audit_key(job):
    sub, h, defines, measured = job
    sf = R.subfamilies()[sub]
    retail = sf.folder / ('perm_%s.dxbc' % h)
    row = {'subfamily': sub, 'hash': h}
    with tempfile.TemporaryDirectory(prefix='d3audit_') as td:
        out = Path(td) / ('u_%s.dxbc' % h)
        cmd = [find_fxc(), '/nologo', '/T', sf.profile, '/E', sf.uber_entry, '/Fo', str(out),
               '/I', str(sf.folder), '/I', str(R.D3_RE)]
        for k, v in defines.items():
            cmd += ['/D', ('%s=%s' % (k, v)) if v not in (None, '') else k]
        cmd.append(str(sf.folder / 'uber.hlsl'))
        r = subprocess.run(cmd, capture_output=True, text=True)
        if r.returncode or not out.exists():
            row.update(status='compile', detail=(r.stderr or r.stdout).strip()[-200:])
            return row
        try:
            DX.asm_path(out, refresh=True)
            probs = D2.compare(D2.retail_surface(retail), DX.surface(out, slang=False))
            row['d2'] = probs[:4]
            ref = DF.Leg.load(retail, slang=False)
            cand = DF.Leg.load(out, slang=False)
            res = DF.compare_slot(ref, cand, measured, DR.slot_seed(h), DF.input_formats(retail))
            row.update(status=res.status, worst_rel=res.worst_rel, wide=res.wide_worst,
                       ties=[res.ties_achieved, res.tie_mismatch], detail=res.error[:200])
        except Exception as e:                               # noqa: BLE001
            tb = traceback.extract_tb(e.__traceback__)[-1]
            row.update(status='exception', detail='%s: %s @%s:%d' % (type(e).__name__, str(e)[:120],
                                                                    Path(tb.filename).name, tb.lineno))
    return row


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--jobs', type=int, default=max(1, (os.cpu_count() or 2) - 4))
    ap.add_argument('--subfamily', action='append', default=[])
    args = ap.parse_args(argv)
    jobs = []
    for d, s in R.bundles():
        for slot in M.load(R.bundle_id(d, s)):
            for r in slot['retail']:
                if args.subfamily and r['subfamily'] not in args.subfamily:
                    continue
                jobs.append((r['subfamily'], r['hash'], r['defines'], slot['measured']))
    with ProcessPoolExecutor(args.jobs) as ex:
        rows = list(ex.map(audit_key, jobs, chunksize=2))
    if args.subfamily:
        for r in rows:
            print(json.dumps(r))
        return 0
    (M.OUT / '_spec_audit.json').write_text(json.dumps(rows, indent=1) + '\n', 'utf-8')
    per = defaultdict(list)
    for r in rows:
        per[r['subfamily']].append(r)
    lines = ['# RE uber spec audit', '',
             'Generated by `tools/d3_spec_audit.py`: each retail key rebuilt from its subfamily\'s',
             '`uber.hlsl` (SDK fxc) and judged like a slang candidate -- D2 declaration surface and',
             'the D4 differential (full schedule, outputs by semantic, tie trials, wide mode).',
             '', '**exact / order-only / fail** count keys by behaviour; **D2** counts keys whose',
             'declarations differ from retail. A subfamily with fails or one-sided output',
             'semantics is a specification to read with suspicion.', '',
             '| Subfamily | Keys | exact | order-only | fail | other | D2 differs | First problem |',
             '|---|---:|---:|---:|---:|---:|---:|---|']
    total = Counter()
    for sub in sorted(per):
        rs = per[sub]
        c = Counter(r['status'] for r in rs)
        total.update(c)
        d2 = sum(1 for r in rs if r.get('d2'))
        first = next((r.get('detail') or '; '.join(r.get('d2') or []) for r in rs
                      if r['status'] not in ('exact', 'order-only')), '') or \
            next(('D2: ' + r['d2'][0] for r in rs if r.get('d2')), '')
        other = len(rs) - c['exact'] - c['order-only'] - c['fail']
        lines.append('| `%s` | %d | %d | %d | %d | %d | %d | %s |'
                     % (sub, len(rs), c['exact'], c['order-only'], c['fail'], other, d2,
                        first.replace('|', '/')[:160]))
    lines += ['', 'Totals: %s over %d keys.' % (dict(total), len(rows))]
    (M.OUT / '_spec_notes.md').write_text('\n'.join(lines) + '\n', 'utf-8')
    print('keys %d: %s' % (len(rows), dict(total)))
    print('D2 differs on %d keys' % sum(1 for r in rows if r.get('d2')))
    return 0


if __name__ == '__main__':
    sys.exit(main())
