"""Extract the BLS template *layout metadata* the rebuild needs into JSON.

``build_bls.py`` repacks Slang-compiled bytecode into the shipped BLS
container shape. To match the shipped files byte-for-byte it needs four
pieces of per-permutation metadata from the originals — and **only** these
four, none of which is shader program code:

  1. the null-perm pattern (which perm slots are zero-length),
  2. each live perm's ``stage`` id,
  3. each live perm's 44-byte resource-binding chunk (opaque engine
     metadata copied verbatim into the v1.8 DX output), and
  4. each live perm's ISGN (input-signature descriptors) — used to align
     our over-declared signature to the shipped layout.

The shipped DXBC program body (SHEX/instructions), RDEF, STAT, OSGN, the
hash, etc. are all regenerated by slangc + build_bls and are never read.
This script pulls just (1)–(4) out of ``war3.w3mod/shaders`` and writes
``wc3_bls_templates.json`` so pipelines can run the whole rebuild without the
shipped shader binaries present.

The per-perm tables are heavily redundant (e.g. hd.bls's 512 perms use
only ~15 distinct binding chunks and ~5 distinct signatures), so the JSON
stores distinct-value pools and references them by index — the whole file
is a few KB.

Usage:
  extract_templates.py --templates war3.w3mod/shaders [-o wc3_bls_templates.json]
"""

import argparse
import json
import os
import sys
from pathlib import Path

from shader_config import load_families
from build_bls import read_template, read_metal_template_nulls

REPO_ROOT = Path(__file__).resolve().parent


def _isgn_to_json(entries):
    """Serialise one ISGN entry list (bytes-keyed tuples from
    ``_parse_isgn_entries``) to JSON-safe rows. Names are ASCII semantic
    strings (already uppercased by the parser)."""
    return [[name.decode('ascii'), sem_idx, sys_val, comp_ty, reg, mask_rw]
            for (name, sem_idx, sys_val, comp_ty, reg, mask_rw) in entries]


def extract_dx(template_path):
    """Build the dedup'd DX section for one family from a shipped DX BLS.

    Returns a dict with ``middle_chunks`` (hex pool), ``isgns`` (signature
    pool) and ``perms`` (per-perm references / null markers)."""
    tmpl = read_template(template_path)

    mid_pool, mid_index = [], {}
    isgn_pool, isgn_index = [], {}
    perms = []

    for i in range(tmpl['num_perms']):
        mid = tmpl['middle_chunks'][i]
        if mid is None:
            perms.append(None)
            continue

        mid_hex = mid.hex()
        if mid_hex not in mid_index:
            mid_index[mid_hex] = len(mid_pool)
            mid_pool.append(mid_hex)

        isgn_rows = _isgn_to_json(tmpl['isgns'][i])
        isgn_key = json.dumps(isgn_rows, separators=(',', ':'))
        if isgn_key not in isgn_index:
            isgn_index[isgn_key] = len(isgn_pool)
            isgn_pool.append(isgn_rows)

        perms.append({
            'm': mid_index[mid_hex],
            's': isgn_index[isgn_key],
            'stage': tmpl['stages'][i],
        })

    return {
        'middle_chunks': mid_pool,
        'isgns': isgn_pool,
        'perms': perms,
    }, tmpl['num_perms']


def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--templates', required=True,
                    help='directory containing ps/*.bls, vs/*.bls and '
                         'mtlfs/*.bls, mtlvs/*.bls (the shipped BLS bundles)')
    ap.add_argument('-o', '--output',
                    default=str(REPO_ROOT / 'wc3_bls_templates.json'),
                    help='output JSON path (default: %(default)s)')
    ap.add_argument('--family', action='append',
                    help='limit to specific family (repeatable; default: all)')
    ap.add_argument('--verbose', '-v', action='store_true')
    args = ap.parse_args()

    families = load_families()
    names = args.family or list(families)

    out_families = {}
    for fam in names:
        if fam not in families:
            print(f'unknown family {fam!r}', file=sys.stderr)
            return 2
        cfg = families[fam]
        entry = {'stage': cfg.stage, 'num_perms': cfg.perm_count}
        have_any = False

        # DX (ps/ or vs/).
        dx_path = os.path.join(args.templates, cfg.dx_dir,
                               cfg.effective_template)
        if os.path.isfile(dx_path):
            dx, num_perms = extract_dx(dx_path)
            if num_perms != cfg.perm_count:
                print(f'WARN {fam}: DX template has {num_perms} perms, '
                      f'config says {cfg.perm_count}', file=sys.stderr)
            entry['dx'] = dx
            have_any = True
            if args.verbose:
                print(f'  {fam} dx: {len(dx["middle_chunks"])} middle, '
                      f'{len(dx["isgns"])} isgn, {len(dx["perms"])} perms')

        # Metal (mtlfs/ or mtlvs/) — null pattern only.
        m_path = os.path.join(args.templates, cfg.metal_dir,
                              cfg.effective_template)
        if os.path.isfile(m_path):
            nulls = read_metal_template_nulls(m_path, cfg.perm_count)
            entry['metal'] = {'nulls': nulls}
            have_any = True
            if args.verbose:
                print(f'  {fam} metal: {sum(nulls)} null / {len(nulls)} perms')

        if have_any:
            out_families[fam] = entry
        elif args.verbose:
            print(f'  {fam}: no template found, skipped')

    doc = {
        '_comment': 'Extracted BLS layout metadata (null pattern, stage, '
                    '44-byte resource-binding chunk, ISGN) for build_bls.py. '
                    'Contains no shader program code. Regenerate with '
                    'extract_templates.py when targeting a new game patch.',
        'families': out_families,
    }
    with open(args.output, 'w') as fp:
        json.dump(doc, fp, indent=1)
        fp.write('\n')

    print(f'wrote {args.output}: {len(out_families)} families')
    return 0


if __name__ == '__main__':
    sys.exit(main())
